version: '3.4'

volumes:
  poptape_items:
    name: poptape_items

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/items/api:v0.1
    ports:
      - "1242:8003"
    restart: always
    depends_on:
      - mongodb
    volumes:
      - /var/log:${LOGFILE}
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape

  mongodb:
    image: mongo
    ports:
      - "1243:27017"
    restart: always
    volumes:
      - poptape_items:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - net_poptape

networks:
  net_poptape:
    external: true

