services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "PORT=${PORT}"
    image: poptape/items/api:v${VERSION}
    ports:
      - "1242:${PORT}"
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ${LOCAL_LOG_LOC}:/items/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - poptape

  mongodb:
    image: mongo
    ports:
      - "1243:27017"
    restart: always
    volumes:
      - poptape_items_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - poptape

networks:
  poptape:
    external: true
volumes:
  poptape_items_data:
    name: poptape_items_data

